ALTER TABLE users ADD COLUMN IF NOT EXISTS sheet_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS folder_id VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_api_key VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS open_doc BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS open_sheet BOOLEAN DEFAULT FALSE;

UPDATE users SET open_doc = FALSE WHERE open_doc IS NULL;
UPDATE users SET open_sheet = FALSE WHERE open_sheet IS NULL;

ALTER TABLE users ALTER COLUMN open_doc SET NOT NULL;
ALTER TABLE users ALTER COLUMN open_sheet SET NOT NULL;
